import { Karta } from "./types";

const Spil: Karta[] = [
    { value: 1, shape: "heart"},
    { value: 2, shape: "heart"},
    { value: 3, shape: "heart"},
    { value: 4, shape: "heart"},
    { value: 5, shape: "heart"},
    { value: 6, shape: "heart"},
    { value: 7, shape: "heart"},
    { value: 8, shape: "heart"},
    { value: 9, shape: "heart"},
    { value: 10, shape: "heart"},
    { value: 11, shape: "heart"},
    { value: 12, shape: "heart"},
    { value: 13, shape: "heart"},

    { value: 1, shape: "diamond"},
    { value: 2, shape: "diamond"},
    { value: 3, shape: "diamond"},
    { value: 4, shape: "diamond"},
    { value: 5, shape: "diamond"},
    { value: 6, shape: "diamond"},
    { value: 7, shape: "diamond"},
    { value: 8, shape: "diamond"},
    { value: 9, shape: "diamond"},
    { value: 10, shape: "diamond"},
    { value: 11, shape: "diamond"},
    { value: 12, shape: "diamond"},
    { value: 13, shape: "diamond"}, 

    { value: 1, shape: "club"},
    { value: 2, shape: "club"},
    { value: 3, shape: "club"},
    { value: 4, shape: "club"},
    { value: 5, shape: "club"},
    { value: 6, shape: "club"},
    { value: 7, shape: "club"},
    { value: 8, shape: "club"},
    { value: 9, shape: "club"},
    { value: 10, shape: "club"},
    { value: 11, shape: "club"},
    { value: 12, shape: "club"},
    { value: 13, shape: "club"},

    { value: 1, shape: "spade"},
    { value: 2, shape: "spade"},
    { value: 3, shape: "spade"},
    { value: 4, shape: "spade"},
    { value: 5, shape: "spade"},
    { value: 6, shape: "spade"},
    { value: 7, shape: "spade"},
    { value: 8, shape: "spade"},
    { value: 9, shape: "spade"},
    { value: 10, shape: "spade"},
    { value: 11, shape: "spade"},
    { value: 12, shape: "spade"},
    { value: 13, shape: "spade"},
]


export default Spil;

export const Level1Info = [
    { id: 1, className: "absolute top-[150px] left-[calc(50%-24px)] z-[10]", hidden: false, disabled: false },
    { id: 2, className: "absolute top-[165px] left-[calc(50%-48px)] z-[8]", hidden: false, disabled: true },
    { id: 3, className: "absolute top-[165px] left-[calc(50%-0px)] z-[8]", hidden: false, disabled: true},
    { id: 4, className: "absolute top-[180px] left-[calc(50%-72px)] z-[6]", hidden: false, disabled: true},
    { id: 5, className: "absolute top-[180px] left-[calc(50%-24px)] z-[6]", hidden: false, disabled: true },
    { id: 6, className: "absolute top-[180px] left-[calc(50%+24px)] z-[6]", hidden: false, disabled: true},
    { id: 7, className: "absolute top-[195px] left-[calc(50%-96px)] z-[4]", hidden: false, disabled: true},
    { id: 8, className: "absolute top-[195px] left-[calc(50%-48px)] z-[4]", hidden: false, disabled: true},
    { id: 9, className: "absolute top-[195px] left-[calc(50%-0px)] z-[4]", hidden: false, disabled: true},
    { id: 10, className: "absolute top-[195px] left-[calc(50%+48px)] z-[4]", hidden: false,  disabled: true},

    { id: 11, className: "absolute top-[275px] left-[calc(26%-28px)] z-[4]", hidden:false, disabled:true},
    { id: 12, className:"absolute top-[290px] left-[calc(26%-48px)] z-[6]", hidden: false, disabled: true},
    { id: 13, className:"absolute top-[290px] left-[calc(26%-0px)] z-[6]", hidden: false, disabled: true},
    { id: 14, className:"absolute top-[305px] left-[calc(26%-72px)] z-[8]", hidden: false, disabled: true},
    { id: 15, className:"absolute top-[305px] left-[calc(26%-24px)] z-[8]", hidden: false, disabled: true},
    { id: 16, className:"absolute top-[305px] left-[calc(26%+24px)] z-[8]", hidden: false, disabled: true},
    { id: 17, className:"absolute top-[320px] left-[calc(26%-96px)] z-[10]", hidden: false, disabled: false},
    { id: 18, className:"absolute top-[320px] left-[calc(26%-48px)] z-[10]", hidden: false, disabled: false},
    { id: 19, className:"absolute top-[320px] left-[calc(26%-0px)] z-[10]", hidden: false, disabled: false},
    { id: 20, className:"absolute top-[320px] left-[calc(26%+48px)] z-[10]", hidden: false, disabled: false},

    { id: 21, className: "absolute top-[275px] left-[calc(76%-24px)] z-[4]", hidden: false, disabled: true},
    { id: 22, className: "absolute top-[290px] left-[calc(76%-48px)] z-[6]", hidden: false, disabled: true},
    { id: 23, className: "absolute top-[290px] left-[calc(76%-0px)] z-[6]", hidden: false, disabled: true},
    { id: 24, className: "absolute top-[305px] left-[calc(76%-72px)] z-[8]", hidden: false, disabled: true},
    { id: 25, className: "absolute top-[305px] left-[calc(76%-24px)] z-[8]", hidden: false, disabled: true},
    { id: 26, className: "absolute top-[305px] left-[calc(76%+24px)] z-[8]", hidden: false, disabled: true},
    { id: 27, className: "absolute top-[320px] left-[calc(76%-96px)] z-[10]", hidden: false, disabled: false},
    { id: 28, className: "absolute top-[320px] left-[calc(76%-48px)] z-[10]", hidden: false, disabled: false},
    { id: 29, className: "absolute top-[320px] left-[calc(76%-0px)] z-[10]", hidden: false, disabled: false},
    { id: 30, className: "absolute top-[320px] left-[calc(76%+48px)] z-[10]", hidden: false, disabled: false},
]


